# Generated by Django 3.1 on 2020-10-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='orgimage',
            field=models.ImageField(default='', upload_to='orgimages'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(upload_to='finalimages'),
        ),
    ]
