# Generated by Django 3.1 on 2020-11-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201024_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
